{
 "title": "Odoo Overview",
 "description": "Overview of Odoo Application Health and Performance",
 "tags": [
  "odoo",
  "application",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Odoo Request Rate (per instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(odoo_http_requests_total[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Odoo HTTP 5xx Error Rate (per instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(odoo_http_requests_total{status=~\"5..\"}[5m])) by (instance) / sum(rate(odoo_http_requests_total[5m])) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Odoo Log Entries Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "{ app_name: \"odoo\" }",
     "filterEditorMode": "builder",
     "language": "lucene",
     "metrics": [
      { "type": "count", "id": "1" }
     ],
     "bucketAggs": [
      { "type": "date_histogram", "id": "2", "settings": { "interval": "auto" } }
     ]
    }
   ]
  }
 ]
}